-- ==============================================================================
-- CHIT CHAT TELUGU - COMPLETE SUPABASE DATABASE SCHEMA
-- ==============================================================================
-- Run this complete script in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query -> Run)

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. USERS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  age INTEGER,
  gender TEXT DEFAULT 'Other',
  birthday TEXT,
  country TEXT,
  phone_number TEXT,
  "profileSongUrl" TEXT,
  "statusVideoUrl" TEXT,
  story_views JSONB DEFAULT '[]'::jsonb,
  hidden_story_from TEXT[] DEFAULT '{}'::text[],
  is_verified BOOLEAN DEFAULT true,
  verification_token TEXT,
  reset_token TEXT,
  reset_token_expiry TEXT,
  public_key TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast user search and auth lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);

-- ==============================================================================
-- 3. MESSAGES TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room TEXT NOT NULL,
  sender TEXT NOT NULL,
  "senderId" TEXT,
  "recipientId" TEXT,
  text TEXT DEFAULT '',
  "imageUrl" TEXT,
  "gifUrl" TEXT,
  "stickerUrl" TEXT,
  "fileUrl" TEXT,
  "fileType" TEXT,
  is_pinned BOOLEAN DEFAULT false,
  reply_to JSONB,
  "viewOnce" BOOLEAN DEFAULT false,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for lightning-fast chat queries
CREATE INDEX IF NOT EXISTS idx_messages_room ON public.messages(room);
CREATE INDEX IF NOT EXISTS idx_messages_senderId ON public.messages("senderId");
CREATE INDEX IF NOT EXISTS idx_messages_recipientId ON public.messages("recipientId");
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON public.messages(timestamp DESC);

-- ==============================================================================
-- 4. FRIENDS & FRIEND REQUESTS TABLES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  friend_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_friend_pair UNIQUE (user_id, friend_id)
);

CREATE INDEX IF NOT EXISTS idx_friends_user_id ON public.friends(user_id);
CREATE INDEX IF NOT EXISTS idx_friends_friend_id ON public.friends(friend_id);

CREATE TABLE IF NOT EXISTS public.friend_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  receiver_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_friend_request UNIQUE (sender_id, receiver_id)
);

CREATE INDEX IF NOT EXISTS idx_friend_requests_receiver ON public.friend_requests(receiver_id);
CREATE INDEX IF NOT EXISTS idx_friend_requests_sender ON public.friend_requests(sender_id);

-- ==============================================================================
-- 5. GROUPS & GROUP MEMBERS TABLES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  avatar_url TEXT,
  created_by TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  edit_info_permission TEXT DEFAULT 'all',
  send_messages_permission TEXT DEFAULT 'all',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'member', -- 'admin' or 'member'
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_group_member UNIQUE (group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_members_group_id ON public.group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_user_id ON public.group_members(user_id);

-- ==============================================================================
-- 6. PERMISSIONS & ROW LEVEL SECURITY (RLS)
-- ==============================================================================
-- Disable RLS on application tables to allow backend Service / Anon keys full access
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.friends DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.friend_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members DISABLE ROW LEVEL SECURITY;

-- Grant permissions to public/anon/authenticated roles
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- ==============================================================================
-- 7. STORAGE BUCKET CONFIGURATION (Bucket: 'abcd')
-- ==============================================================================
-- Insert public storage bucket 'abcd' if it does not already exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('abcd', 'abcd', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Ensure public access to 'abcd' bucket for uploads and downloads
CREATE POLICY "Public Access to abcd bucket" ON storage.objects
FOR ALL USING (bucket_id = 'abcd')
WITH CHECK (bucket_id = 'abcd');
